name: 'GitHub Actions Auto Commit Bot'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 19 * * *'

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Working'
        env:
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
          KCODE_KEY: ${{ secrets.KCODE_KEY }}
        run: bash commit.sh